html/protected/controllers/PedidosController.php
<?php

class PedidosController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('update', 'index', 'view', 'admin', 'delete', 'save', 'ajax', 'confirmar', 'repetir', 'repetir2', 'productospedido', 'status', 'mispedidos'),
                'roles' => array('admin'),
            ),
            array('allow',
                'actions' => array('update', 'index', 'view', 'save', 'ajax', 'confirmar', 'repetir', 'repetir2', 'productospedido', 'status', 'mispedidos'),
                'roles' => array('clientes'),
            ),
            array('allow',
                'actions'=>array('create','trae'),
                'users'=>array('*'),
            ),

            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     */
    public function actionView() {
        $id = Yii::app()->request->getParam('id');
        $pedidos = pedidos::model()->with('usuarios')->findByPk($id);
        $pedidosproductos = pedidosproductos::model()->with('productos')->findAll(array(
            'condition' => 'pedido_id=:pedido_id',
            'params' => array(':pedido_id' => $id)
        ));

        $this->render("view", array(
            "pedidos" => $pedidos,
            "pedidosproductos" => $pedidosproductos
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $usuario = usuarios::model()->find(array(
            'select' => 'razon_social',
            'condition' => 'id=:id',
            'params' => array(':id' => Yii::app()->user->id),
        ));

        $model = productos::model()->with('categoria')->findAll(array('order' => 't.id desc'));
        $categorias = categorias::model()->findAll();

        if (isset($_GET['productos']))
            $model->attributes = $_GET['productos'];

        $this->render('create', array(
            'model' => $model,
            'categorias' => $categorias,
            'razon_social' => $usuario->razon_social,
        ));
    }

    public function actionTrae() {
        $status=1;
        $z = new CDbCriteria();
        $c = is_null($_GET["c"]) ? 0 : $_GET["c"];
        $q = isset($_GET["q"]) ? $_GET["q"] : 0;

        if ($c != 0) {
            $z->join = " INNER JOIN categorias c ON c.id = t.categoria_id ";
            $z->addCondition("t.categoria_id = $c");
            $z->addCondition('t.status = :status');
            $z->params = array(':status' => 1);
        }

        if ($q != "0") {
            $z->join = " INNER JOIN categorias c ON c.id = t.categoria_id ";
            $z->addCondition("descripcion LIKE '%$q%' "
                    . "or modelo LIKE '%$q%' "
                    . "or c.categoria LIKE '%$q%'");
            $z->addCondition('t.status = :status');
            $z->params = array(':status' => 1);
        }

        $model = productos::model()->findAll($z);
        $this->renderPartial('trae', array(
            'model' => $model,
        ));
    }

    public function actionSave() {

        $pedidos = new pedidos();
        $cliente_id = $_POST['client_id'];
        $clientes = usuarios::model()->findByPk($cliente_id);
        $email = $clientes->email;
        $pedidos->user_id = $cliente_id;
        $pedidos->date = date('Y-m-d H:i:s');
        $pedidos->status = 1;
        $pedidos->save();
        $prod = $_POST['productos'];
        foreach ($prod as $p) {
            $productos = new pedidosproductos();
            $productos->pedido_id = $pedidos->id;
            $productos->producto_id = $p["producto_id"];
            $productos->cant = $p["cant"];
            $productos->save();
        }
        $subject = "Su pedido ha sido realizado";
        $txt = "Gracias por utilizar nuestro sistema online de pedidos,"
                . " su pedido est&aacute; siendo procesado"
                . "<br/><br/><br/>SIFOLIMP-pedidos web.";
        $headers = "MIME-Version: 1.0\r\n";
        $headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
        $headers .= "From: info@sifolimp.com.ar\r\nReply-To: info@sifolimp.com.ar";
        $res = mail($email, $subject, $txt, $headers);
        if ($res == 1) {
            #echo "Se ha enviado su nueva password al mail.";
        } else {
            #echo "Ha fallado el envio de su nueva password, contactese con el administrador.";
        }

        echo $pedidos->id;
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate() {
        $model = $this->loadModel();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['pedidos'])) {
            $model->attributes = $_POST['pedidos'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel()->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */

    public function actionIndex() {

        $criteria = new CDbCriteria(array(
            'order' => 't.id DESC',
            'with' => array('usuarios')
        ));
        $dataProvider = new CActiveDataProvider('pedidos', array(
            'criteria' => $criteria,
                )
        );

        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {

        #$model = new pedidos('search');
        #$model->unsetAttributes();  // clear any default values
        if (isset($_GET['pedidos']))
            $model->attributes = $_GET['pedidos'];

        $limit = 10;
        $page = isset($_GET['page']) ? $_GET['page'] : 0;
        $offset = $limit * $page;
        $user_id = Yii::app()->user->id;

        if (isset($_GET['cliente'])) {
            
            $cli = $_GET['cliente'];
            $count = pedidos::model()->findAll(
                    array(
                        "condition" => "user_id =  $user_id",
                    )
            );
            $totalItems = count($count);
            $model = pedidos::model()->findAll(
                    array(
                        "condition" => "user_id =  $cli",
                        "order" => "id desc",
                        'limit' => $limit,
                        'offset' => $offset
                    )
            );
        } else {
            $count = pedidos::model()->findAll(
                    array(
                        'order' => 'id desc',
                    )
            );
            $model = pedidos::model()->findAll(
                    array(
                        'order' => 'id desc',
                        'limit' => $limit,
                        'offset' => $offset
                    )
            );
            $totalItems = count($count);
        }
        $cli = (isset($cli)) ? $cli : 0;
        $div = $totalItems / $limit;
        $totalPages = round($div, 0);
        $this->render('admin', array(
            'model' => $model,
            'page' => $page,
            'totalPages' => $totalPages,
            'cli' => $cli
        ));
    }

    public function actionMispedidos() {
        $limit = 10;
        $page = isset($_GET['page']) ? $_GET['page'] : 0;
        $offset = $limit * $page;
        $user_id = Yii::app()->user->id;
        $count = pedidos::model()->findAll(
                array(
                    "condition" => "user_id =  $user_id",
                )
        );
        $totalItems = count($count);
        $model = pedidos::model()->findAll(
                array(
                    "condition" => "user_id =  $user_id",
                    "order" => "id desc",
                    'limit' => $limit,
                    'offset' => $offset
                )
        );
        $div = $totalItems / $limit;
        $totalPages = round($div, 0);
        #print_r($totalItems . " " . $div . " " . $totalPages);
        $this->render('mispedidos', array(
            'model' => $model,
            'page' => $page,
            'totalPages' => $totalPages,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     */
    public function loadModel() {

html/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

html/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

html/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="language" content="en">

        <!-- blueprint CSS framework -->
        <!--
        <link rel="stylesheet" type="text/css" href="<?php #echo Yii::app()->request->baseUrl;  ?>/css/screen.css" media="screen, projection">
        <link rel="stylesheet" type="text/css" href="<?php #echo Yii::app()->request->baseUrl;  ?>/css/print.css" media="print">
        -->
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
        <![endif]-->

        <!--
        <link rel="stylesheet" type="text/css" href="<?php #echo Yii::app()->request->baseUrl;  ?>/css/main.css">
        <link rel="stylesheet" type="text/css" href="<?php #echo Yii::app()->request->baseUrl;  ?>/css/form.css">
        -->

        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/custom.css">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/font-awesome.min.css" >
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/animate.css">

        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="http://www.sifolimp.com.ar/" title="Sifolimp.com.ar">
                        <img alt="Brand" src="img/sifolimp.gif" alt="Sifolimp" />
                    </a>
                </div>


                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="home-vendedor.html">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pedidos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="pedidos-vendedor.html">lista de pedidos<i class="fa fa-bars"></i></a></li>
                            <li><a href="crear-pedidos-vendedor.html">crear pedidos<i class="fa fa-plus"></i></a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Productos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="productos-vendedor.html">lista de productos<i class="fa fa-bars"></i></a></li>
                            <li><a href="crear-producto-vendedor.html">crear productos<i class="fa fa-plus"></i></a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="clientes-vendedor.html">lista de clientes<i class="fa fa-bars"></i></a></li>
                            <li><a href="crear-cliente-vendedor.html">crear clientes<i class="fa fa-plus"></i></a></li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav><!-- /. nav-->


        <div class="container" id="page">

            <div id="header">
                <div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
            </div><!-- header -->

            <div id="mainmenu">                
                <?php
                $this->widget('zii.widgets.CMenu', array(
                    'items' => array(
                        array('label' => 'Homeee', 'url' => array('/site/index'), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Pedidos', 'url' => array('/pedidos/index'), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Productos', 'url' => array('/productos/index'), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Usuariosss', 'url' => array('/usuarios/index'), 'visible' => !Yii::app()->user->isGuest),
                        #array('label' => 'About', 'url' => array('/site/page', 'view' => 'about')),
                        #array('label' => 'Contact', 'url' => array('/site/contact')),
                        array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                        array('label' => 'Logout (' . Yii::app()->user->name . /* Yii::app()->user->rol . */')',
                            'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
                    ),
                ));
                ?>
            </div><!-- mainmenu -->
            <?php if (isset($this->breadcrumbs)): ?>
                <?php
                $this->widget('zii.widgets.CBreadcrumbs', array(
                    'links' => $this->breadcrumbs,
                ));
                ?><!-- breadcrumbs -->
            <?php endif ?>

            <?php echo $content; ?>

            <div class="clear"></div>

            <div id="footer">
                <div class="footer container-fluid">
                    <div class="container">
                        ©2013 Sifolimp
                    </div>
                </div>
            </div><!-- footer -->

        </div><!-- page -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/wow.min.js"></script>
    </body>
</html>