html/protected/models/pedidos.php
<?php

/**
 * This is the model class for table "pedidos".
 *
 * The followings are the available columns in table 'pedidos':
 * @property string $id
 * @property string $user_id
 * @property string $date
 * @property string $cat
 */
class pedidos extends CActiveRecord {

    #public $razon_social;
    #public $nombre;
    #public $apellido;
    #public $cant;

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'pedidos';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('user_id', 'required'),
            array('user_id', 'length', 'max' => 11),
            array('date', 'length', 'max' => 45),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('id, user_id, date, nombre, apellido, razon_social', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(            
            'productos' => array(self::MANY_MANY, 'productos', 'pedidosproductos(pedido_id,producto_id)'),
            'usuarios' => array(self::BELONGS_TO, 'usuarios', 'user_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'Id',
            'user_id' => 'User',
            'date' => 'Date',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search() {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.        
        $criteria = new CDbCriteria;
        $criteria->with = array("usuarios");
        $criteria->compare('id', $this->id, true);
        $criteria->compare('user_id', $this->user_id, true);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('razon_social', $this->razon_social, true);
        $criteria->compare('apellido', $this->apellido, true);
        $criteria->compare('nombre', $this->nombre, true);
        return new CActiveDataProvider('pedidos', array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * @return pedidos the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

}

html/protected/controllers/UsuariosController.php
<?php

class UsuariosController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('create', 'update', 'index', 'view', 'admin', 'delete', 'assign', 'buscar', 'status','changepassword'),
                'roles' => array('admin'),
            ),
            array('allow',
                'actions' => array('update', 'index', 'view', 'assign', 'buscar', 'status','changepassword'),
                'roles' => array('clientes'),
            ),
            array('allow',
                'actions' => array('update', 'index', 'view', 'assign', 'buscar', 'status','changepassword'),
                'roles' => array('vendedores'),
            ),
            array('allow',
                'actions' => array('enviar'),
                'users' => array('*'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     */
    public function actionView() {
        $this->render('view', array(
            'model' => $this->loadModel(),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        #Uncomment the following line if AJAX validation is needed
        #$this->performAjaxValidation($model);

        $model = new usuarios;
        $model->setScenario('create');
        $authitems = Array();
        foreach (Yii::app()->authManager->getAuthItems() as $data) {
            $authitems[$data->type] = $data->name;
        }

        if (isset($_POST['usuarios'])) {

            $model->email = $_POST['usuarios']['email'];
            $model->password = md5($_POST['usuarios']['password']);
            $model->razon_social = $_POST['usuarios']['razon_social'];
            $model->cuit = $_POST['usuarios']['cuit'];
            $model->nombre = $_POST['usuarios']['nombre'];
            $model->apellido = $_POST['usuarios']['apellido'];
            $model->type = $_POST['usuarios']['type'];

            if ($model->save()) {
                $this->actionAssign($model->id, $authitems[$model->type]);
                $this->redirect(array('admin'));
            }
        }

        $this->render('create', array(
            'model' => $model,
            'authitems' => $authitems,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate() {
        $model = $this->loadModel();
        $authitems = Array();
        foreach (Yii::app()->authManager->getAuthItems() as $data) {
            $authitems[$data->type] = $data->name;
        }

        if (isset($_POST['usuarios'])) {
            $model->setScenario('update');

            $model->email = $_POST['usuarios']['email'];
            $model->nombre = $_POST['usuarios']['nombre'];
            $model->apellido = $_POST['usuarios']['apellido'];
            $model->type = $_POST['usuarios']['type'];

            if ($model->update()) {
                foreach (Yii::app()->authManager->getAuthItems() as $data) {
                    Yii::app()->authManager->revoke($data->name, $model->id);
                }
                if(isset($_POST['usuarios']['type'])){
                    $this->actionAssign($model->id, $authitems[$_POST['usuarios']['type']]);
                }
                if (Yii::app()->user->checkAccess('admin')) {
                    $this->redirect("/usuarios/admin");
                } else {
                    $this->redirect("/pedidos/mispedidos/");
                }
            }
        }

        if (Yii::app()->user->checkAccess('clientes') || Yii::app()->user->checkAccess('venderores')) {
            if ($_GET['id'] != Yii::app()->user->id) {
                $this->redirect(array('update', 'id' => Yii::app()->user->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
            'authitems' => $authitems,
        ));
    }

    public function actionChangepassword() {

        $model = usuarios::model()->findByPk(Yii::app()->user->id);
        $model->setScenario('changepassword');

        if (isset($_POST['usuarios'])) {

            $model->attributes = $_POST['usuarios'];
            $valid = $model->validate();

            if($valid){ 

                $model->password = md5($model->new_password);

                if($model->save()){
                    $this->redirect(array('changepassword','msg'=>'password actualizada correctamente'));
                    if (Yii::app()->user->checkAccess('admin')) {
                        $this->render('admin');
                    } else {
                        $this->render('mispedidos');
                    }
                }else{
                    $this->redirect(array('changepassword','msg'=>'password no actualizada'));
                }
            }
        }
        $this->render('changepassword',array('model'=>$model)); 
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel()->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('usuarios');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $tipo = 4;
        if (isset($_GET['tipo']))
            $tipo = $_GET['tipo'];

        if ($tipo == 4) {
            $model = usuarios::model()->findAll(array(
                "order" => "id desc",
            ));
        } else {
            $model = usuarios::model()->findAll(array(
                "condition" => "type =  $tipo",
                "order" => "id desc",
            ));
        }

        if (isset($_GET['usuarios']))
            $model->attributes = $_GET['usuarios'];

        $this->render('admin', array('model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     */
    public function loadModel() {
        if ($this->_model === null) {
            if (isset($_GET['id']))
                $this->_model = usuarios::model()->findbyPk($_GET['id']);
            if ($this->_model === null)
                throw new
                CHttpException(404, 'The requested page does not exist.');
        }
        return $this->_model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'usuarios-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionAssign($id, $item) {
        Yii::app()->authManager->assign($item, $id);
    }

    public function actionBuscar() {
        $key = $_POST["cliente"];
        $q = new CDbCriteria(array(
            'condition' => "razon_social LIKE :cliente",
            'params' => array(':cliente' => "%$key%")
        ));
        $clientes = usuarios::model()->findAll($q);
        foreach ($clientes as $cliente) {
            $country_name = str_replace($_POST['cliente'], '<b>' . $_POST['cliente'] . '</b>', $cliente ['razon_social']);
#echo '<li onclick="set_item(\'' . str_replace("'", "\'", $cliente['razon_social']) . '\')">' . $country_name . '</li>';
            echo '<li onclick="set_item(' . $cliente['id'] . ',\'' . $cliente ['razon_social'] . '\')">' . $country_name . '</li>';
        }
        Yii::app()->end();
    }

    public function actionEnviar() {
        $key = $_POST["email"];
        $clientes = usuarios::model()->find("email = '$key'");

        if ($clientes) {
            $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            $password = substr(str_shuffle($chars), 0, 8);
            $clientes->password = $password;
            $clientes->save();
            $headers = "MIME-Version: 1.0\r\n";
            $headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
            $headers .= "From: info@sifolimp.com\r\nReply-To: info@sifolimp.com";
            $res = mail($key, "Nueva password sifolimp", " Su nueva password sifolimp es: $password", $headers);
            if ($res == 1) {
                echo "Se ha enviado su nueva password al mail.";
            } else {

html/protected/views/pedidos/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date'); ?>
		<?php echo $form->textField($model,'date',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

html/protected/views/pedidos/_view.php
<div class="view">

    <b><?php echo CHtml::encode($data->getAttributeLabel('Pedido')); ?>:</b>
    <?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
    <br />

    <!--
    <b><?php #echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
    <?php #echo CHtml::encode($data->user_id); ?>
    <br />
    -->
    
    <b><?php echo CHtml::encode($data->getAttributeLabel('usuario')); ?>:</b>
    <?php echo CHtml::encode($data->usuarios->razon_social) . ", " . 
            CHtml::encode($data->usuarios->cuit); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
    <?php echo CHtml::encode($data->date); ?>
    <br />

    <!--
    <?php #foreach ($data->productos as $pp): ?>
        <h3>pedido_id :<?php #echo ($pp->pedido_id); ?></h3>
        <h3>producto_id :<?php #echo ($pp->producto_id); ?></h3>
    <?php #endforeach; ?>    
    <br/>
    -->

</div>

html/protected/views/pedidos/admin.php
<style type="text/css">
    .input_container ul {
        width: 206px;
        border: 1px solid #eaeaea;
        position: absolute;
        z-index: 9;
        background: #f3f3f3;
        list-style: none;
    }
    .input_container ul li {
        padding: 2px;
    }
    .input_container ul li:hover {
        background: #eaeaea;
    }
    #country_list_id {
        display: none;
    }
</style>

<script type="text/javascript">

    function changestatus(pedido) {

        var pedido_id = $(pedido).attr('pedido_id');
        var status = pedido.value;
        var msj = "Estas seguro que desea cambiar el status del pedido?";
        if (confirm(msj)) {
            $.ajax({
                url: '/pedidos/status',
                type: 'POST',
                data: {pedido_id: pedido_id, status: status},
                success: function(data) {
                    console.log("OK" + data);
                    if(status == 1){
                        $(pedido).parent().parent().css("color", "#000000");
                    }else{
                        $(pedido).parent().parent().css("color", "green");
                    }
                },
                error: function(err) {
                    console.log("ERR" + err);
                }
            });
        }

    }

    function autocomplet() {
        var min_length = 3; // min caracters to display the autocomplete
        var keyword = $('#client_id').val();
        if (keyword.length >= min_length) {
            $.ajax({
                url: '/usuarios/buscar',
                type: 'POST',
                data: {cliente: keyword},
                success: function(data) {
                    //alert(data);
                    $('#client_list_id').show();
                    $('#client_list_id').html(data);
                },
                error: function(err) {
                    $('#client_list_id').show();
                    $('#client_list_id').html(err);
                }
            });
        } else {
            $('#client_list_id').hide();
        }
    }

// set_item : this function will be executed when we select an item
    function set_item(id, razon_social) {
        // change input value
        $('#client_id').val(razon_social);
        $("#client_id").attr("client_id", id);
        // hide proposition list
        $('#client_list_id').hide();
    }

    function buscarporclinte() {
        var cliente = $("#client_id").attr("client_id");
        if (!cliente) {
            $("#popup-selecciona-cliente").modal();
        } else {
            window.location = "/pedidos/admin/cliente/" + cliente;
        }
    }

</script>

<?php
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#pedidos-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div class="container-fluid search">
    <div class="container">
        <div class="row">       
            <div class="col-md-offset-5 col-md-2"></div>
            <?php if (!Yii::app()->user->checkAccess('clientes')) { ?>
                <div class="col-md-3">
                    <div class="input_container">
                        <input type="text" id="client_id" client_id=""
                               class="form-control" onkeyup="autocomplet()"
                               placeholder="Razon social del cliente">
                        <ul id="client_list_id"></ul>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="btn-login" onclick="buscarporclinte()">Buscar por cliente</div>
                </div>
                <br/><br/><br/>
            <?php } ?>
            <a href="/pedidos/create" >
                <div class="btn-login goto">crear nuevo pedido</div>
            </a>
        </div>
    </div>
</div>



<div class="container">
    <?php if ($model != null): ?>
        <table class="table table-striped">
            <tr>
                <td>Pedido</td>
                <td>Cliente Razon Social</td>
                <td>Fecha</td>
                <td>Status</td>
                <td>Ver</td>
            </tr>
            <?php foreach ($model as $data): ?>
                <tr <?php if ($data->status == 3) { ?> style="color:green;" <?php } ?>>
                    <td><?php echo $data->id; ?></td>
                    <td><?php echo $data->usuarios->razon_social; ?></td>
                    <td><?php echo $data->date; ?></td>
                    <td>
                        <?php if (Yii::app()->user->checkAccess('admin')) { ?>
                            <select class="select-options" pedido_id="<?php echo $data->id; ?>" onchange="changestatus(this)">
                                <option value="1" <?php if ($data->status == 1) { ?>selected <?php } ?>>En proceso</option>
                                <option value="3" <?php if ($data->status == 3) { ?>selected <?php } ?>>Entregado</option>
                                <?php #} ?>
                            </select>
                        <?php } else { ?>
                            <?php
                            if ($data->status == 1) {
                                echo "En proceso";
                            }
                            if ($data->status == 2) {
                                echo "En despacho";
                            }
                            if ($data->status == 3) {
                                echo "Entregado";
                            }
                        }
                        ?>
                    </td>


                    <td>
                        <a href = "/pedidos/view/<?php echo $data->id; ?>" class = "editbtn">
                            <i class = "fa fa-eye"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    <nav>
        <ul class="pagination">
            <li>
                <a href="/pedidos/admin<?php
                if (($cli != 0)) {
                    echo "/cliente/" . $cli;
                }
        ?>?page=<?php echo $page - 1; ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
                <?php
                for ($i = 0; $i < $totalPages; $i++) {
                    ?>
                <li <?php if ($page == $i) { ?>
                        echo class = "active"
                    <?php } ?>>
                    <a href="/pedidos/admin<?php
                           if (($cli != 0)) {
                               echo "/cliente/" . $cli;
                           }
                           ?>?page=<?php echo $i; ?>">
    <?php echo $i + 1; ?>
                    </a>
                </li>
                <?php } ?>
            <li>
                <a href="/pedidos/admin<?php
                if (($cli != 0)) {
                    echo "/cliente/" . $cli;
                }
                ?>?page=<?php echo $page + 1; ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    <div style="clear: both;"></div>
    *Nota: para pedidos fuera de Capital y GBA el estado "ENTREGADO" implica entregado en transporte seleccionado por el cliente.
</div>

<div class="modal fade" id="popup-selecciona-cliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>Selecciona un cliente.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Aceptar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

html/protected/views/pedidos/index.php
<?php
$this->breadcrumbs = array(
    'Pedidoses',
);

$this->menu = array(
    array('label' => 'Create pedidos', 'url' => array('create')),
    array('label' => 'Manage pedidos', 'url' => array('admin')),
);
?>

<h1>Pedidoses</h1>

<?php
$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_view',
    #'pager' => array("htmlOptions"=>array("class"=>"pagination")),
));
?>

html/protected/views/pedidos/mispedidos.php
<style type="text/css">
    .input_container ul {
        width: 206px;
        border: 1px solid #eaeaea;
        position: absolute;
        z-index: 9;
        background: #f3f3f3;
        list-style: none;
    }
    .input_container ul li {
        padding: 2px;
    }
    .input_container ul li:hover {
        background: #eaeaea;
    }
    #country_list_id {
        display: none;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $('#select-options-status').on('change', function() {
            var pedido_id = $(this).attr('pedido_id');
            var status = this.value;
            var msj = "Estas seguro que desea cambiar el status del pedido?";
            if (confirm(msj)) {
                $.ajax({
                    url: '/pedidos/status',
                    type: 'POST',
                    data: {pedido_id: pedido_id, status: status},
                    success: function(data) {
                        console.log("OK" + data);
                    },
                    error: function(err) {
                        console.log("ERR" + err);
                    }
                });
            }

        });

    });

    function autocomplet() {
        var min_length = 3; // min caracters to display the autocomplete
        var keyword = $('#client_id').val();
        if (keyword.length >= min_length) {
            $.ajax({
                url: '/usuarios/buscar',
                type: 'POST',
                data: {cliente: keyword},
                success: function(data) {
                    //alert(data);
                    $('#client_list_id').show();
                    $('#client_list_id').html(data);
                },
                error: function(err) {
                    $('#client_list_id').show();
                    $('#client_list_id').html(err);
                }
            });
        } else {
            $('#client_list_id').hide();
        }
    }

// set_item : this function will be executed when we select an item
    function set_item(id, razon_social) {
        // change input value
        $('#client_id').val(razon_social);
        $("#client_id").attr("client_id", id);
        // hide proposition list
        $('#client_list_id').hide();
    }

    function buscarporclinte() {
        var cliente = $("#client_id").attr("client_id");
        if (!cliente) {
            alert("Selecciona un cliente");
        } else {
            window.location = "/pedidos/admin/cliente/" + cliente;
        }
    }

</script>
<?php
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#pedidos-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div class="container-fluid search">
    <div class="container">
        <div class="row">       
            <div class="col-md-offset-5 col-md-2"></div>
            <?php if (!Yii::app()->user->checkAccess('clientes')) { ?>
                <div class="col-md-3">
                    <div class="input_container">
                        <input type="text" id="client_id" client_id=""
                               class="form-control" onkeyup="autocomplet()"
                               placeholder="Razon social del cliente">
                        <ul id="client_list_id"></ul>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="btn-login" onclick="buscarporclinte()">Buscar por cliente</div>
                </div>
                <br/><br/><br/>
            <?php } ?>
            <a href="/pedidos/create" >
                <div class="btn-login goto">crear nuevo pedido</div>
            </a>
        </div>
    </div>
</div>



<div class="container">
    <?php if ($model != null): ?>
        <table class="table table-striped">
            <tr>
                <td>Pedido</td>
                <td>Cliente Razon Social</td>
                <td>Fecha</td>                
                <td>Status</td>
                <td>Ver</td>
            </tr>
            <?php foreach ($model as $data): ?>
                <?php #print_r($data); ?>
                <?php #print_r($data->usuarios); ?>
                <?php #print_r($data->pedidos); ?>
                <?php #exit; ?>
                <tr>
                    <td><?php echo $data->id; ?></td>
                    <td><?php echo $data->usuarios->razon_social; ?></td>
                    <td><?php echo $data->date; ?></td>
                    <td>
                        <?php if ($data->status == 1) { ?>En proceso<?php } ?>
                        <?php if ($data->status == 2) { ?>En despacho <?php } ?>
                        <?php if ($data->status == 3) { ?>Entregado<?php } ?>
                    </td>
                    <td>
                        <a href = "/pedidos/view/<?php echo $data->id; ?>" class = "editbtn">
                            <i class = "fa fa-eye"></i>
                        </a>
                    </td>
                    <!--
                    <td>
                    <a href = "#" class = "editbtn">
                    <i class = "fa fa-trash"></i>
                    </a>
                    </td>
                    -->
                </tr>
                <?php #echo $data->name;  
                ?>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>


    <?php #echo CHtml::link('Advanced Search','#',array('class'=>'search-button'));        ?>
    <div class="search-form" style="display:none">
        <?php
        /*
          $this->renderPartial('_search', array(
          'model' => $model,
          ));
         */
        ?>
    </div><!-- search-form -->    
    <nav>
        <ul class="pagination">
            <li>
                <a href="/pedidos/mispedidos?page=<?php echo 0; ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <?php for ($i = 0; $i < $totalPages; $i++) { ?>
                <li <?php if ($page == $i) { ?>
                        echo class = "active"
                    <?php } ?>>
                    <a href="/pedidos/mispedidos?page=<?php echo $i; ?>">
                           <?php echo $i + 1; ?>
                    </a>
                </li>
            <?php } ?>
            <li>
                <a href="/pedidos/mispedidos?page=<?php echo $totalPages-1; ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    <div style="clear: both;"></div>
    *Nota: para pedidos fuera de Capital y GBA esto implica entregado en transporte seleccionado por el cliente.
</div>
<?php
/*
  $this->widget('zii.widgets.grid.CGridView', array(
  'id' => 'pedidos-grid',
  'dataProvider' => $model->search(),
  'filter' => $model,
  'columns' => array(
  #'id',
  #'user_id',
  array(
  'header' => 'Razon social',
  'name' => 'razon_social',
  'value' => '$data->usuarios->razon_social',
  'filter' => CHtml::activeTextField($model, 'razon_social'),
  ),
  array(
  'header' => 'nombre',
  'name' => 'nombre',
  'value' => '$data->usuarios->nombre',
  ),
  array(
  'header' => 'apellido',
  'name' => 'apellido',
  'value' => '$data->usuarios->apellido',
  ),
  'date',
  #array(
  #    'class' => 'CButtonColumn',
  #),
  array(
  'header' => '',
  'class' => 'CButtonColumn',
  'viewButtonImageUrl' => Yii::app()->baseUrl . '/css/gridViewStyle/images/' . 'gr-view.png',
  #'updateButtonImageUrl' => Yii::app()->baseUrl .
  #'/css/gridViewStyle/images/' . 'gr-update.png',
  'updateButtonImageUrl' => "<i class='fa fa-pencil'></i>",
  #<a href="editar-pedido.html" class="editbtn">
  #<i class="fa fa-pencil"></i></a>
  'deleteButtonImageUrl' => Yii::app()->baseUrl . '/css/gridViewStyle/images/' . 'gr-delete.png',
  ),
  ),
  ));
 */
?>