html/protected/models/productos.php
<?php

/**
 * This is the model class for table "productos".
 *
 * The followings are the available columns in table 'productos':
 * @property string $id
 * @property string $codigo
 * @property string $descripcion
 * @property string $marca
 * @property string $modelo
 * @property string $categoria
 * @property string $embalaje
 * @property string $nombre_foto
 * @property string $precio
 * @property string $status
 * 
 * The followings are the available model relations:
 * @property Pedidos[] $pedidoses
 */
class productos extends CActiveRecord {

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'productos';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            #array('nombre_foto', 'file', 'allowEmpty' => false),
            #array('nombre_foto', 'file', 'types' => 'jpg,jpeg', 'maxSize' => 30720),
            #array('codigo, descripcion, marca, modelo, categoria, embalaje, nombre_foto', 'precio', 'length', 'max' => 255),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            // array('categoria', 'integerOnly' => true),
            #array('id, codigo, descripcion, marca, modelo, categoria, embalaje, nombre_foto', 'precio', 'safe', 'on' => 'search'),
            array('codigo, descripcion, marca, modelo, categoria_id,precio,nombre_foto', 'required',
                'on' => 'create',
                'message' => 'Por favor escriba un valor para {attribute}.'),
            array('codigo, descripcion, marca, modelo, categoria_id,precio', 'required',
                'on' => 'update',
                'message' => 'Por favor escriba un valor para {attribute}.'),
            array('precio,embalaje,status', 'safe'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'pedidos' => array(self::MANY_MANY, 'pedidos', 'pedidosproductos(producto_id,pedido_id,cant)'),
            'categoria' => array(self::BELONGS_TO, 'categorias', 'categoria_id')
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'Id',
            'codigo' => 'Codigo',
            'descripcion' => 'Descripcion',
            'marca' => 'Marca',
            'modelo' => 'Modelo',
            'categoria_id' => 'Categoria',
            'embalaje' => 'Embalaje',
            'nombre_foto' => 'Foto',
            'precio' => 'Precio',
            'status' => 'Status',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models 
     * based on the search/filter conditions.
     */
    public function search() {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;
        $criteria->compare('id', $this->id, true);
        $criteria->compare('codigo', $this->codigo, true);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('marca', $this->marca, true);
        $criteria->compare('modelo', $this->modelo, true);
        $criteria->compare('categoria_id', $this->categoria_id, true);
        $criteria->compare('embalaje', $this->embalaje, true);
        $criteria->compare('nombre_foto', $this->nombre_foto, true);
        $criteria->compare('precio', $this->precio, true);
        $criteria->compare('status', $this->status, true);
        return new CActiveDataProvider('productos', array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * @return productos the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

}

html/protected/controllers/ProductosController.php
<?php

class ProductosController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                #'controllers' => array("users"),
                'actions' => array('create','update', 'index', 'view', 'admin', 'delete', 'UpdatePrecio','pdf', 'pdf2','status'),
                'roles' => array('admin'),
            ),

            array('allow',
                'actions'=>array('trae'),
                'users'=>array('*'),
            ),

            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     */
    public function actionView() {
        $this->render('view', array(
            'model' => $this->loadModel(),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new productos;
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['productos'])) {
            $model->setScenario('create');
            $model->attributes = $_POST['productos'];
            $res = $model->validate();
            $res2 = $model->getErrors();
            $uf = CUploadedFile::getInstance($model, 'nombre_foto');
            $name = $uf ? $uf->getName() : NULL;
            $model->nombre_foto = $name;
            if ($model->save()) {
                if ($uf) {
                    $uf->saveAs(Yii::getPathOfAlias("webroot") . "/images/" . $name);
                }
                $this->redirect(array('admin'));
            }
        }
        $categorias = categorias::model()->findAll();
        $cate = Array();

        foreach ($categorias as $categoria) {
            $cate[$categoria->id] = $categoria->categoria;
        }

        $this->render('create', array(
            'model' => $model,
            'categorias' => $cate,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate() {
        $model = $this->loadModel();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['productos'])) {
            $model->setScenario('update');
            $model->attributes = $_POST['productos'];
            $uf = CUploadedFile::getInstance($model, 'nombre_foto');
            $model->nombre_foto = $uf ? $uf->getName() : $model->nombre_foto;
            if ($model->save()) {
                if ($uf) {
                    $uf->saveAs(Yii::getPathOfAlias("webroot") . "/images/" . $model->nombre_foto);
                }
                $this->redirect(array('view', 'id' => $model->id));
            }
        }
        $categorias = categorias::model()->findAll();
        $cate = Array();
        foreach ($categorias as $categoria) {
            $cate[$categoria->id] = $categoria->categoria;
        }
        $this->render('update', array(
            'model' => $model,
            'categorias' => $cate,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete() {

        if (isset($_GET['id'])) {
            $id = $_GET['id'];
            $productos = productos::model()->findByPk($id);
            $productos->delete();
            $this->redirect(array('admin'));
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('productos');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */

    public function actionAdmin() {

        if (isset($_GET['productos']))
            $model->attributes = $_GET['productos'];


        $limit = 15;
        $page = isset($_GET['page']) ? $_GET['page'] : 0;
        $offset = $limit * $page;
        $model = productos::model()->with('categoria')->findAll(
                array(
                    'order' => 't.id desc',
                    'limit' => $limit,
                    'offset' => $offset
                )
        );
        $totalItems = productos::model()->count();
        $div = $totalItems / $limit;
        $totalPages = round($div, 0);
        $this->render('admin', array(
            'model' => $model,
            'page' => $page,
            'totalPages' => $totalPages,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     */
    public function loadModel() {
        if ($this->_model === null) {
            if (isset($_GET['id']))
                $this->_model = productos::model()->findbyPk($_GET['id']);
            if ($this->_model === null)
                throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $this->_model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'productos-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionUpdatePrecio() {
        if (isset($_POST['id']) and isset($_POST['precio'])) {
            $id = $_POST['id'];
            $precio = $_POST['precio'];
            $productos = productos::model()->findByPk($id);
            $productos->precio = $precio;
            $productos->save();
        }else{
            echo "Faltan datos";
        }      
    }

    public function actionTrae() {
        $p = $_POST['productos'];
        $ids = Array();
        foreach ($p as $pp) {
            array_push($ids, $pp['producto_id']);
        }
        $criteria = new CDbCriteria();
        $criteria->addInCondition("id", $ids);
        $result = productos::model()->findAll($criteria);
        #print_r(json_encode($result));exit;
        echo CJSON::encode($result);exit;
    }

    public function actionPdf() {

        $model = productos::model()->with('categoria')->findAll(
                array(
                    'order' => 't.id desc',
                )
        );

        $this->render('pdf', array(
            'model' => $model,
        ));
    }

       public function actionPdf2() {

        $model = productos::model()->with('categoria')->findAll(
                array(
                    'order' => 't.id desc',
                )
        );

        $pdf=Yii::app()->pdfFactory->getTCPDF(); 
        $tbl = "";
        $con=mysqli_connect("localhost","root","root");  
        mysqli_select_db($con, "sifolimp_db");  
        $result = mysqli_query($con,"SELECT codigo,descripcion,marca,modelo,embalaje,precio from productos limit 2");
        if (($result)){  
            $tbl .= "<div>";
            if (mysqli_num_rows($result)>0){   
                $tbl .= "<div>";  
                while ($property =  mysqli_fetch_field($result)){  
                    $tbl .= "<div><b>" . $property->name . "</b></div>"; 
                }  
                $tbl .= "</div>";
                while ($rows = mysqli_fetch_array($result,MYSQL_ASSOC)){
                    $tbl .= "<div>";
                    foreach ($rows as $data){  
                        $tbl .= "<div>" . $data . "</div>";  
                    }
                    $tbl .= "</div>";
                }  
            }else{  
            }
            $tbl .= "</div>";
            $pdf->writeHTML($tbl, true, false, true, false);
        }else{  
            #echo "Error in running query :". mysql_error(); 
        }

        $pdf->Output('example_011.pdf', 'I');

    }


    public function actionStatus() {
        $product_id = $_POST["product_id"];
        $status = $_POST["status"];

        $result = productos::model()->updateByPk($product_id, array(
            'status' => $status
        ));
        if ($result) {
            echo "OK";
        } else {
            echo "ERROR";
        }
    }

}

html/protected/views/productos/_form.php
<?php
$marcas = array("Sifolimp" => "Sifolimp", "Aqcua" => "Aqcua");
#print_r($categorias);exit;
?>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3 well well-lg campos-form">
            <div class="form">
                <?php
                $form = $this->beginWidget('CActiveForm', array(
                    'id' => 'productos-form',
                    'enableAjaxValidation' => false,
                    'htmlOptions' => array('enctype' => 'multipart/form-data'),
                ));
                ?>
                <h2>
                    <?php
                    if ($model->isNewRecord) {
                        echo 'Crea un nuevo producto';
                    } else {
                        echo 'Editar producto';
                    }
                    ?>
                </h2>
                <?php #echo $form->errorSummary($model); ?>

                <div class="input-group">
                    <label>Codigo</label>
                    <?php echo $form->textField($model, 'codigo', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'codigo'); ?>
                </div>
                <div class="input-group">
                    <label>Descripcion</label>
                    <?php echo $form->textField($model, 'descripcion', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'descripcion'); ?>
                </div>                    
                <div class="dropdown">
                    <label>Marca</label>
                    <?php
                    echo $form->dropDownList($model, 'marca', $marcas, array(
                        'prompt' => 'Seleccionar'
                    ));
                    ?>
                    <?php echo $form->error($model, 'marca'); ?>
                </div>
                <div class="input-group">
                    <label>Modelo</label>
                    <?php echo $form->textField($model, 'modelo', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'modelo'); ?>
                </div>
                <div class="input-group">
                    <label>Categoria</label>
                    <?php
                    echo $form->dropDownList($model, 'categoria_id', $categorias, array(
                        'prompt' => 'Seleccionar'
                    ));
                    ?>
                    <?php echo $form->error($model, 'categoria_id'); ?>
                </div>
                <div class="input-group">
                    <label>Embalaje</label>
                    <?php echo $form->textField($model, 'embalaje', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'embalaje'); ?>
                </div>                
                <div class="input-group">
                    <label>Imagen</label>
                    <?php #echo $form->textField($model, 'nombre_foto', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control'));  ?>
                    <!--<input type="file" class="form-control" placeholder="" aria-describedby="basic-addon1">-->
                    <?php echo $form->fileField($model, 'nombre_foto'); ?>
                    <?php echo $form->error($model, 'nombre_foto'); ?>
                </div>
                <div class="input-group">
                    <label>Precio</label>
                    <?php echo $form->textField($model, 'precio', array('size' => 60, 'maxlength' => 6, 'class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'precio'); ?>
                </div>
                <?php echo CHtml::submitButton($model->isNewRecord ? 'Cargar' : 'Guardar', array('class' => 'btn-login')); ?>
                <?php $this->endWidget(); ?>
            </div>
        </div>
    </div>
</div>
<?php
#if(Yii::app()->user->hasFlash("nombre_foto")) {
#    echo CHtml::image(Yii::app()->request->baseUrl."".Yii::app()->user->getFlash("nombre_foto"));
#}
?>

html/protected/views/productos/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'codigo'); ?>
		<?php echo $form->textField($model,'codigo',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'descripcion'); ?>
		<?php echo $form->textField($model,'descripcion',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'marca'); ?>
		<?php echo $form->textField($model,'marca',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'modelo'); ?>
		<?php echo $form->textField($model,'modelo',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'categoria'); ?>
		<?php echo $form->textField($model,'categoria',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'embalaje'); ?>
		<?php echo $form->textField($model,'embalaje',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nombre_foto'); ?>
		<?php echo $form->textField($model,'nombre_foto',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

html/protected/views/productos/_view.php
<div class="view">

    <!--
    <b><?php #echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
    <?php #echo CHtml::link(CHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
    <br />
    -->

    <b><?php echo CHtml::encode($data->getAttributeLabel('codigo')); ?>:</b>
    <?php echo CHtml::link(CHtml::encode($data->codigo), array('view', 'id' => $data->id)); ?>
    <?php #echo CHtml::encode($data->codigo); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('marca')); ?>:</b>
    <?php echo CHtml::encode($data->marca); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('categoria')); ?>:</b>
    <?php echo CHtml::encode($data->categoria->categoria); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('descripcion')); ?>:</b>
    <?php echo CHtml::encode($data->descripcion); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('modelo')); ?>:</b>
    <?php echo CHtml::encode($data->modelo); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('embalaje')); ?>:</b>
    <?php echo CHtml::encode($data->embalaje); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('nombre_foto')); ?>:</b><br />
    <img src="/images/<?php echo CHtml::encode($data->nombre_foto); ?>" width="50"/>
    <br />

</div>

html/protected/views/productos/admin.php
<script>
    function precios(prod) {
        if (confirm('Seguro que desea cambiar el precio al producto?')) {
            console.log(prod.value);
            console.log($(prod).attr("id"));
            var id = $(prod).attr("id");
            var precio = prod.value;
            $.ajax({
                url: '/productos/UpdatePrecio',
                type: 'POST',
                data: {id: id, precio: precio},
                success: function(data) {
                    console.log("OK" + data);
                },
                error: function(err) {
                    console.log("NO" + err);

                }
            });
        } else {
            console.log("Cancelado");
            location.reload();
        }
    }

    function status(data) {
        var product_id = $(data).attr('product_id');
        var status = data.value;
        $.ajax({
            url: '/productos/status',
            type: 'POST',
            data: {product_id: product_id, status: status},
            success: function(data) {
                console.log(data);
                $("#modal-product-status").modal();
            },
            error: function(err) {
                console.log(data);
            }
        });
    }

</script>

<?php
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#productos-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div class="container">
    <a href="/productos/create" >
        <div class="btn-login goto">crear nuevo producto
        </div>
    </a>
    <?php if ($model != null): ?>
        <table class="table table-striped">
            <tr>
                <td>Código</td>
                <td>Marca</td>
                <td>Categoría</td>
                <td>Descripción</td>
                <td>Modelo</td>
                <td>Embalaje</td>
                <td>Estado</td>
                <td>Foto</td>
                <td>Ver</td>
            </tr>
            <?php foreach ($model as $data): ?>
                <tr>
                    <td><?php echo $data->codigo; ?></td>
                    <td><?php echo $data->marca; ?></td>
                    <td><?php echo $data->categoria->categoria; ?></td>
                    <td><?php echo $data->descripcion; ?></td>
                    <td><?php echo $data->modelo; ?></td>
                    <td><?php echo $data->embalaje; ?></td>
                    <td>
                        <select class="select-options" onchange="status(this)" product_id="<?php echo $data->id; ?>">
                            <option value="0" <?php if ($data->status == 0) { ?> selected <?php } ?>>Deshabilitado</option>
                            <option value="1" <?php if ($data->status == 1) { ?> selected <?php } ?>>Habilitado</option>
                        </select>
                    </td>
                    <td class="list-image">
                        <img src="/images/<?php echo $data->nombre_foto; ?>" 
                             alt="producto" />
                    </td>
                    <td>
                        <a href="/productos/<?php echo $data->id; ?>" class="editbtn">
                            <i class="fa fa-eye"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>

    <nav>
        <ul class="pagination">
            <li>
                <a href="/productos/admin?page=<?php echo 0; ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <?php for ($i = 0; $i < $totalPages; $i++) { ?>
                <li <?php if ($page == $i) { ?>
                        echo class = "active"
                    <?php } ?>>
                    <a href="/productos/admin?page=<?php echo $i; ?>">
                        <?php echo $i + 1; ?>
                    </a>
                </li>
            <?php } ?>
            <li>
                <a href="/productos/admin?page=<?php echo $totalPages - 1; ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

<div class="modal fade" id="modal-product-status" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>El estado del producto ha cambiado.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Aceptar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

html/protected/views/productos/create.php
<?php echo $this->renderPartial('_form', array('model'=>$model, 'categorias' => $categorias)); ?>

html/protected/views/productos/index.php
<?php

?>

<?php foreach ($dataProvider as $producto): ?>
    <h3><?php #print_r($producto); ?></h3>
    <h3><?php #echo $producto->nombre_foto;   ?></h3>
<?php endforeach; ?>

<?php
$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_view',
        #'pager' => array("htmlOptions" => array("class" => "pagination")),
        #'columns'=>array(
        #    'codigo',
        #    'descripcion',
        #    'marca',
        #    'modelo',
        #    'categoria',
        #   'emabalaje',
        #),
));
?>

html/protected/views/productos/pdf.php
<script type="text/javascript" src="/js/base64.js"></script>
<script type="text/javascript" src="/js/sprintf.js"></script>


<script type="text/javascript" src="/js/jspdf.js"></script>
<script type="text/javascript" src="/js/standard_fonts_metrics.js"></script>
<script type="text/javascript" src="/js/split_text_to_size.js"></script>
<script type="text/javascript" src="/js/from_html.js"></script>


<script type="text/javascript">

    function PDF1(){
        var doc = new jsPDF('p', 'in', 'letter');
        var source = $('#pdf').html();
        var specialElementHandlers = {
            '#bypassme': function(element, renderer) {
            return true;
            }
        };

        console.log("hola");

       doc.fromHTML(source, 0.5, 0.5,
        {
            'width': 7.5, // max width of content on PDF
            'elementHandlers': specialElementHandlers
        });

        console.log("hola2");

        doc.output('dataurl');
    }

    $(document).ready(function() {
        //PDF1();
    });


</script>
<!--
<div class="container">
    <div class="btn-login goto" onclick="print()">IMPRIMIR</div>
</div>
-->

<div class="container" id="pdf">
<!--
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="http://www.sifolimp.com.ar/" title="Sifolimp.com.ar">
                    <img alt="Brand" src="/images/sifolimp.gif" alt="Sifolimp" />
                </a>
            </div>
        </div>   
    </nav>   
-->
<?php if ($model != null): ?>
    <table class="table table-striped">
        <tr>
            <td>Código</td>
            <td>Marca</td>                
            <td>Categoría</td>
            <td>Descripción</td>
            <td>Modelo</td>                
            <td>Embalaje</td>
            <td>Precio</td>
        </tr>
        <?php foreach ($model as $data): ?>
            <tr>
                <td><?php echo $data->codigo; ?></td>
                <td><?php echo $data->marca; ?></td>                    
                <td><?php echo $data->categoria->categoria; ?></td>
                <td><?php echo $data->descripcion; ?></td>
                <td><?php echo $data->modelo; ?></td>
                <td><?php echo $data->embalaje; ?></td>
                <td>$<?php echo $data->precio; ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
</div>

html/protected/views/productos/pdf2.php
<?php

/*
require_once('tcpdf.php');
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetAuthor('Ignacio Mariano Gonzalez');
$pdf->SetTitle('Sifolimp');
$pdf->SetSubject('Sifolimp');
$pdf->SetKeywords('Sifolimp');
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);

$pdf->setPrintHeader("Sifo");
$pdf->setPrintFooter("Sifo");

#$pdf->SetMargins(10, PDF_MARGIN_TOP, 10);

$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
$pdf->SetFont('helvetica', '', 10);
error_reporting(E_ALL) ; ini_set('display_errors', '1');  
$con=mysqli_connect("localhost","root","root");   
if(!$con){  
  die('Could not connect: ' . mysql_error());  
}   
$tbl = "";
mysqli_select_db($con, "sifolimp_db");  
$result = mysqli_query($con,"SELECT codigo,descripcion,marca,modelo,embalaje,precio from productos limit 2");
if (($result)){  
    $tbl .= "<div>";
    if (mysqli_num_rows($result)>0){   
        $tbl .= "<div>";  
        while ($property =  mysqli_fetch_field($result)){  
            $tbl .= "<div><b>" . $property->name . "</b></div>"; 
        }  
        $tbl .= "</div>";
        while ($rows = mysqli_fetch_array($result,MYSQL_ASSOC)){
            $tbl .= "<div>";
            foreach ($rows as $data){  
                $tbl .= "<div>" . $data . "</div>";  
            }
            $tbl .= "</div>";
        }  
    }else{  
    }
    $tbl .= "</div>";
    #print_r($tbl);exit;
    $pdf->writeHTML($tbl, true, false, true, false);
}else{  
  #echo "Error in running query :". mysql_error(); 
}

$pdf->Output('example_011.pdf', 'I');
*/
?>

html/protected/views/productos/update.php
<?php echo $this->renderPartial('_form', array('model' => $model, 'categorias' => $categorias)); ?>