html/protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'

        if (Yii::app()->user->isGuest) {
            $this->redirect("/site/login");
        }
        $categorias = categorias::model()->findAll();

        $z = new CDbCriteria();
        $c = isset($_GET["c"]) ? $_GET["c"] : 0;
        $q = isset($_GET["q"]) ? $_GET["q"] : 0;
        if ($c != "0") {
            $z->join = 'INNER JOIN categorias c ON c.id= t.categoria_id';
            $z->addCondition("t.categoria_id = $c");
        }

        if ($q != "0") {#&& $_GET["q"] != 0
            $z->addCondition("descripcion LIKE '%$q%' or modelo LIKE '%$q%'");
        }
        $model = productos::model()->with('categoria')->findAll($z);

        $this->render('index', array(
            'model' => $model,
            'categorias' => $categorias,
            'cate' => $c,
            'desc' => $q,
        ));
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $name = '=?UTF-8?B?' . base64_encode($model->name) . '?=';
                $subject = '=?UTF-8?B?' . base64_encode($model->subject) . '?=';
                $headers = "From: $name <{$model->email}>\r\n" .
                        "Reply-To: {$model->email}\r\n" .
                        "MIME-Version: 1.0\r\n" .
                        "Content-Type: text/plain; charset=UTF-8";

                mail(Yii::app()->params['adminEmail'], $subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(Yii::app()->user->returnUrl);
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

}

html/protected/controllers/UsuariosController.php
<?php

class UsuariosController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('create', 'update', 'index', 'view', 'admin', 'delete', 'assign', 'buscar', 'status','changepassword'),
                'roles' => array('admin'),
            ),
            array('allow',
                'actions' => array('update', 'index', 'view', 'assign', 'buscar', 'status','changepassword'),
                'roles' => array('clientes'),
            ),
            array('allow',
                'actions' => array('update', 'index', 'view', 'assign', 'buscar', 'status','changepassword'),
                'roles' => array('vendedores'),
            ),
            array('allow',
                'actions' => array('enviar'),
                'users' => array('*'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     */
    public function actionView() {
        $this->render('view', array(
            'model' => $this->loadModel(),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        #Uncomment the following line if AJAX validation is needed
        #$this->performAjaxValidation($model);

        $model = new usuarios;
        $model->setScenario('create');
        $authitems = Array();
        foreach (Yii::app()->authManager->getAuthItems() as $data) {
            $authitems[$data->type] = $data->name;
        }

        if (isset($_POST['usuarios'])) {

            $model->email = $_POST['usuarios']['email'];
            $model->password = md5($_POST['usuarios']['password']);
            $model->razon_social = $_POST['usuarios']['razon_social'];
            $model->cuit = $_POST['usuarios']['cuit'];
            $model->nombre = $_POST['usuarios']['nombre'];
            $model->apellido = $_POST['usuarios']['apellido'];
            $model->type = $_POST['usuarios']['type'];

            if ($model->save()) {
                $this->actionAssign($model->id, $authitems[$model->type]);
                $this->redirect(array('admin'));
            }
        }

        $this->render('create', array(
            'model' => $model,
            'authitems' => $authitems,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate() {
        $model = $this->loadModel();
        $authitems = Array();
        foreach (Yii::app()->authManager->getAuthItems() as $data) {
            $authitems[$data->type] = $data->name;
        }

        if (isset($_POST['usuarios'])) {
            $model->setScenario('update');

            $model->email = $_POST['usuarios']['email'];
            $model->nombre = $_POST['usuarios']['nombre'];
            $model->apellido = $_POST['usuarios']['apellido'];
            $model->type = $_POST['usuarios']['type'];

            if ($model->update()) {
                foreach (Yii::app()->authManager->getAuthItems() as $data) {
                    Yii::app()->authManager->revoke($data->name, $model->id);
                }
                if(isset($_POST['usuarios']['type'])){
                    $this->actionAssign($model->id, $authitems[$_POST['usuarios']['type']]);
                }
                if (Yii::app()->user->checkAccess('admin')) {
                    $this->redirect("/usuarios/admin");
                } else {
                    $this->redirect("/pedidos/mispedidos/");
                }
            }
        }

        if (Yii::app()->user->checkAccess('clientes') || Yii::app()->user->checkAccess('venderores')) {
            if ($_GET['id'] != Yii::app()->user->id) {
                $this->redirect(array('update', 'id' => Yii::app()->user->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
            'authitems' => $authitems,
        ));
    }

    public function actionChangepassword() {

        $model = usuarios::model()->findByPk(Yii::app()->user->id);
        $model->setScenario('changepassword');

        if (isset($_POST['usuarios'])) {

            $model->attributes = $_POST['usuarios'];
            $valid = $model->validate();

            if($valid){ 

                $model->password = md5($model->new_password);

                if($model->save()){
                    $this->redirect(array('changepassword','msg'=>'password actualizada correctamente'));
                    if (Yii::app()->user->checkAccess('admin')) {
                        $this->render('admin');
                    } else {
                        $this->render('mispedidos');
                    }
                }else{
                    $this->redirect(array('changepassword','msg'=>'password no actualizada'));
                }
            }
        }
        $this->render('changepassword',array('model'=>$model)); 
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel()->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('usuarios');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $tipo = 4;
        if (isset($_GET['tipo']))
            $tipo = $_GET['tipo'];

        if ($tipo == 4) {
            $model = usuarios::model()->findAll(array(
                "order" => "id desc",
            ));
        } else {
            $model = usuarios::model()->findAll(array(
                "condition" => "type =  $tipo",
                "order" => "id desc",
            ));
        }

        if (isset($_GET['usuarios']))
            $model->attributes = $_GET['usuarios'];

        $this->render('admin', array('model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     */
    public function loadModel() {
        if ($this->_model === null) {
            if (isset($_GET['id']))
                $this->_model = usuarios::model()->findbyPk($_GET['id']);
            if ($this->_model === null)
                throw new
                CHttpException(404, 'The requested page does not exist.');
        }
        return $this->_model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'usuarios-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionAssign($id, $item) {
        Yii::app()->authManager->assign($item, $id);
    }

    public function actionBuscar() {
        $key = $_POST["cliente"];
        $q = new CDbCriteria(array(
            'condition' => "razon_social LIKE :cliente",
            'params' => array(':cliente' => "%$key%")
        ));
        $clientes = usuarios::model()->findAll($q);
        foreach ($clientes as $cliente) {
            $country_name = str_replace($_POST['cliente'], '<b>' . $_POST['cliente'] . '</b>', $cliente ['razon_social']);
#echo '<li onclick="set_item(\'' . str_replace("'", "\'", $cliente['razon_social']) . '\')">' . $country_name . '</li>';
            echo '<li onclick="set_item(' . $cliente['id'] . ',\'' . $cliente ['razon_social'] . '\')">' . $country_name . '</li>';
        }
        Yii::app()->end();
    }

    public function actionEnviar() {
        $key = $_POST["email"];
        $clientes = usuarios::model()->find("email = '$key'");

        if ($clientes) {
            $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            $password = substr(str_shuffle($chars), 0, 8);
            $clientes->password = $password;
            $clientes->save();
            $headers = "MIME-Version: 1.0\r\n";
            $headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
            $headers .= "From: info@sifolimp.com\r\nReply-To: info@sifolimp.com";
            $res = mail($key, "Nueva password sifolimp", " Su nueva password sifolimp es: $password", $headers);
            if ($res == 1) {
                echo "Se ha enviado su nueva password al mail.";
            } else {

html/protected/views/site/about.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name . ' - About';
$this->breadcrumbs=array(
	'About',
);
?>
<h1>About</h1>

<p>This is a "static" page. You may change the content of this page
by updating the file <code><?php echo __FILE__; ?></code>.</p>

html/protected/views/site/contact.php
<script type="text/javascript">
    $(document).ready(function() {
        console.log("ready!");
    });
</script>

<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name . ' - Contact Us';
$this->breadcrumbs = array(
    'Contact',
);
?>

<h1>Contact Us</h1>

<?php if (Yii::app()->user->hasFlash('contact')): ?>

    <div class="flash-success">
        <?php echo Yii::app()->user->getFlash('contact'); ?>
    </div>

<?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="form">

        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'contact-form',
            'enableClientValidation' => true,
            'clientOptions' => array(
                'validateOnSubmit' => true,
            ),
        ));
        ?>

        <p class="note">Fields with <span class="required">*</span> are required.</p>

            <?php echo $form->errorSummary($model); ?>

        <div class="row">
            <?php echo $form->labelEx($model, 'name'); ?>
    <?php echo $form->textField($model, 'name'); ?>
    <?php echo $form->error($model, 'name'); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model, 'email'); ?>
    <?php echo $form->textField($model, 'email'); ?>
    <?php echo $form->error($model, 'email'); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model, 'subject'); ?>
    <?php echo $form->textField($model, 'subject', array('size' => 60, 'maxlength' => 128)); ?>
    <?php echo $form->error($model, 'subject'); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model, 'body'); ?>
    <?php echo $form->textArea($model, 'body', array('rows' => 6, 'cols' => 50)); ?>
        <?php echo $form->error($model, 'body'); ?>
        </div>

            <?php if (CCaptcha::checkRequirements()): ?>
            <div class="row">
                    <?php echo $form->labelEx($model, 'verifyCode'); ?>
                <div>
        <?php $this->widget('CCaptcha'); ?>
        <?php echo $form->textField($model, 'verifyCode'); ?>
                </div>
                <div class="hint">Please enter the letters as they are shown in the image above.
                    <br/>Letters are not case-sensitive.</div>
            <?php echo $form->error($model, 'verifyCode'); ?>
            </div>
            <?php endif; ?>

        <div class="row buttons">
        <?php echo CHtml::submitButton('Submit'); ?>
        </div>

    <?php $this->endWidget(); ?>

    </div><!-- form -->

<?php endif; ?>

html/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

html/protected/views/site/index.php
<?php
/* @var $this SiteController */
$this->pageTitle = Yii::app()->name;
?>

<style type="text/css">
    #test { 
        height: 30px;
        width: 150px;
        border: 1px #000 solid;
    }
    #test li { padding: 5px 10px; z-index: 2; }
    #test li:not(.init) { float: left; width: 130px; display: none; background: #ddd; }
    #test li:not(.init):hover, #test li.selected:not(.init) { background: #09f; }
    li.init { cursor: pointer; }

    a#submit { z-index: 1; }

    .sticky {position: fixed; top: 0; width: 100%; z-index: 100; border-bottom: 4px solid #ffffff; }
</style>

<script type="text/javascript">

    function buscar() {
        var buscar = $("#buscar_home").val();
        var categoria = $(".select-options").val();
        console.log(categoria);
        if (categoria && buscar) {
            window.location = "/site/index/c/" + categoria + "/q/" + buscar;
        } else if (categoria && !buscar) {
            window.location = "/site/index/c/" + categoria;
        } else if (!categoria && buscar) {
            window.location = "/site/index/q/" + buscar;
        }
    }

    function select(obj) {
        alert(obj);
        //var buscar = $("#buscar_home").val();
        //window.location = "/site/index/q/" + buscar;
    }

    $(window).scroll(function() {
        if ($(this).scrollTop() > 1) {
            $('.search').addClass("sticky");
        }
        else {
            $('.search').removeClass("sticky");
        }
    });</script>

<div class="container-fluid search">
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-4 col-sm-3">
                <!--<select class="selectpicker">-->
                <select class="select-options">
                    <option selected disabled>Categorias</option>
                    <?php foreach ($categorias as $categoria) { ?>
                        <option value="<?php echo $categoria->id; ?>"
                        <?php if (isset($cate) and $cate != 0) { ?>
                            <?php if ($categoria->id == $cate) { ?>
                                        selected=""
                                    <?php } ?>
                                <?php } ?>
                                >
                                    <?php echo $categoria->categoria; ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-3">
                <div class="input-group">
                    <input type="text" id="buscar_home" class="form-control" 
                    <?php if (isset($desc) and $desc != 0) { ?>
                               placeholder="<?php echo $desc; ?>"
                           <?php } else { ?>
                               placeholder="Buscas algo en particular?"
                           <?php } ?>
                           >
                    <span class="input-group-addon" onclick="buscar()">
                        <i class="fa fa-search"></i>
                    </span>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="btn-login" onclick="buscar()">buscar</div>
            </div>
        </div> <!-- /busqueda -->
    </div><!-- /container-->
</div><!-- /containet fluid-->
<div class="container">
    <div class="articulos clearfix">
        <h2>Productos</h2>
        <?php if ($model != null) { ?>
            <ul class="articulos-list buy" id="lista-pedidos">
                <?php foreach ($model as $data): ?>
                    <?php #print_r($data);exit; ?>
                    <li>
                        <div class="producto-imagen">
                            <img src="/images/<?php echo $data->nombre_foto; ?>" 
                                 alt="producto" />
                        </div>
                        <p><span>Codigo:</span><?php echo $data->codigo; ?> </p>
                        <p><span>Marca: </span><?php echo $data->marca; ?> </p>
                        <p><span>Categoria: </span><?php echo $data->categoria->categoria; ?></p>
                        <p><span>Descripcion:</span><?php echo substr($data->descripcion, 0, 15); ?> </p>                      
                        <p><span>Modelo:</span><?php echo substr($data->modelo, 0, 20); ?><p>

                        <p><span>Embalaje:</span> <?php echo substr($data->embalaje, 0, 16); ?></p>
                    </li>
                <?php endforeach; ?>
                <div style="clear: both; height: 10px;"></div>
            </ul>
        <?php }else { ?>
            <h2>No se encontraron productos con esa descripcion</h2>
            <div class="col-sm-2">
                <div class="btn-login"><a href="/site/index" style="color:white;">Ir al inicio</a></div>
            </div>

        <?php } ?>
    </div>
</div>

html/protected/views/site/login.php
<script type="text/javascript">

    function isValidEmailAddress(emailAddress) {
        var pattern = new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
        return pattern.test(emailAddress);
    }

    //function cerrar() {
    //$('#passwordforgotten').modal('hide');
    //}


    $(document).ready(function() {
        $(".forgetpass").click(function() {
            var pattern = new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
            var email = $(".form-control").val();
            console.log(email);
            var result = pattern.test(email);
            if (result === true) {
                $.ajax({
                    url: '/usuarios/enviar',
                    type: 'POST',
                    data: {email: email},
                    success: function(data) {
                        //console.log("OK " + data);
                        $("#errorlogin").show().html(data).delay(6000).fadeOut();
                        //$("#enviar_password_forgotten").click(false);
                        //$("#enviar_password_forgotten").hide();
                        //setInterval(function(){cerrar()}, 6000);
                    },
                    error: function(err) {
                        console.log("ERROR " + err.responseText);
                    }
                });
            } else {
                $("#errorlogin").show().html("Ingrese un mail valido").delay(4000).fadeOut();
            }


        });
    });

</script>

<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle = Yii::app()->name . ' - Login';
?>

<div class="logo">
    <img src="/images/sifolimp2.gif" alt="Sifolimp" /> 
</div>
<div class="login-box clearfix">
    <div class="form">
        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'login-form',
            'enableClientValidation' => true,
            'clientOptions' => array(
                'validateOnSubmit' => true,
            ),
        ));
        ?>

        <div class="content-form">
            <form class="email-login">
                <label>Email:</label>
                <div class="input-group margin-bottom-sm">
                    <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                    <?php #echo $form->labelEx($model, 'Email'); ?>
                    <!--<input class="form-control" type="text" />-->
                    <div id="username">
                        <?php echo $form->textField($model, 'username', array('class' => 'form-control')); ?>
                    </div>
                    <?php echo $form->error($model, 'username'); ?>
                </div>
                <label>Contraseña:</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                    <!--<input class="form-control" type="password" />-->
                    <div style="clear: both;"></div>
                    <?php echo $form->passwordField($model, 'password', array('class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'password'); ?>
                </div>
                <?php #echo $form->checkBox($model, 'rememberMe'); ?>
                <?php #echo $form->label($model, 'rememberMe'); ?>
                <?php #echo $form->error($model, 'rememberMe'); ?>
                <div class="forgetpass"><a href="#" title="olvide mi contraseña">Olvide mi contraseña</a></div>
                &nbsp;<p id="errorlogin" class="min"></p>
                <?php
                if ($model->hasErrors()) {
                    #echo CHtml::errorSummary($model);
                }
                ?>

                <?php echo CHtml::submitButton('INGRESAR', array('class' => 'btn-login')); ?>
                <!--
                <div class="goto-register">No tienes cuenta? 
                    <span><a href="/usuarios/create">Crear cuenta</a></span>
                </div>
                -->
            </form>
            <?php $this->endWidget(); ?>    
        </div><!-- /.content-form-->
    </div><!-- Modal -->
</div>

<!-- Modal -->
<!--
<div class="modal fade" id="passwordforgotten" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Escribe tu email para que te enviemos una nueva contraseña</h4>
            </div>
            <div class="modal-body">
                <div class="content-form">
                    <form class="email-login">
                        <div class="input-group margin-bottom-sm">
                            <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
                            <input class="form-control" type="text" id="email_password_forgotten"/>
                        </div>
                    </form>
                </div>
            </div>
            &nbsp;<p id="errorlogin" class="min"></p>
            <div class="modal-footer">
                <div class="btn-login" id="enviar_password_forgotten">Enviar</div>
            </div>
        </div>
    </div>
</div>
-->